travis:
  secure:
    BINSTAR_TOKEN: bG6hqZqwLpM4Rs1OlDVFcl+HrnF8J8RxVdY/EVClqE262Rcb5ttC9QP5ofIBHM/ztRS5lU4fFQYPW97PmKCRJlSvNJU2qJ9fCWO+fshorPYjFCvWqsC1IRpkQ01FGjkb1bYn9S5knW+tp3rLqRFpASvpW+TDmiVZwyK37PLTjqQff0/lK5YZfdoGUoeYzZcGFDb2zPUa+UJ/mKIjruO8owgCifJwtgoO2ompqy+ytDQUz21g5eGC42NUFFtR7Ga399MRAKg9a3ZtG7ZFh0VAaScg4dXBDRZf/G5Yh2TB2qYbQvaPXOJIzg7N5hEpgfowNNcY4xzcBOGOxfuy0ewjArb5oPMdR/Ow+gyEoNGy+JgPGipc+J94YwdjBgKt/ytGvRx4q7Nl41GxjEjsfgOrBFn7siFvL6cR5wqN4Tp8L+pMxtReWK5UN7/VwnAtFi37vZZT4fGMjHa3+aP1z556Zf0HyxrMsGMoNRUH69UuNSCVS9KbE8/fGLj8Vl3expAZ6ryMpBl88MwZ6Do0QTo4lvZz11KxAwEb2hn7Qi1Ma+HQWoC4rfEVYXIU26q01RkwKT5c29FmjLoWnAxFRFCNcrwYzAb0MtMdUmCd20TegM4VoDWaznrxX1qCPYeUuLIXXGWoujaHqoztRG4jZJxYa05hBYC8U1zp1oUe79Ph0A8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
