travis:
  secure:
    BINSTAR_TOKEN: Hds1MlDCeTZuLc0DGEtjvbcS6pw3gjbBzrMfBF0AhJhCwpTA1YeasIiLIjSIIogVutlGDfP3YgKm0eKNPU8AZ39DDP81+6DHL16ZQoh43xdTNUgW1XC+eWHgc9SCP7cCenZKQL0UbI1hy4PEkatTwUnHJwLPhetr7rC6tHt6YAcU8zauHmnYaem9pd1AHdkyJ4w8lcCDKU8iH3WyVWuX2OdxrcC2bIHp1Po03mp/V+Fupnu/sv2sgprrjX+JeyTduGsoCBgCwfUZH/qxofSGOWC9PXnPNLghOlgFV3vQJwosiQT+7DcPXdMD4kprq+UToWz9sc8F2RF5EQV5F0K+WQzoMW7f4wfgmrUF3hiVBMndfkgsbmYQ6r1+lgIWNM61ZgBrHVh5ql775uHa7oDripM2/+YYbE8yP4bTbJXEOgFSVVRydDxhlixfi5IVdyzXdSe50rL+tGkVN+lsGyMCkri/xIkwUVS2lmK+enuxZbKqDSZGXtHPDt0WGXLT08/jZqnG09K+zy0ole7yiravxPMrb3g5j7OTs80UgiG96VlcuxtT6pTRXilr4VQMjjGptGOlZ7WGg8fUDm5GUhZveiTE7GF3eGWZ/87IDqgbKR3E2l75x4PIjutAo3Wiz45z9+FwErK6laJO6o8mEUniM3OsdHKkSVE/6+MOFmDUc1g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
